"""eerste migratie

Revision ID: 3abb270ddd20
Revises: 
Create Date: 2024-03-19 21:14:42.583759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abb270ddd20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('housing_median_age', sa.Float(), nullable=True),
    sa.Column('total_rooms', sa.Float(), nullable=True),
    sa.Column('total_bedrooms', sa.Float(), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('households', sa.Float(), nullable=True),
    sa.Column('median_income', sa.Float(), nullable=True),
    sa.Column('median_house_value', sa.Float(), nullable=True),
    sa.Column('ocean_proximity', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    # ### end Alembic commands ###
